### ISSUE TITLE
Is it not possible to make this extension work anymore?

### ISSUE THREAD

**Issue by 677230756E64** [joshhunt/season-pass-extension#15]
Bungie just made all seasonal content free till June, including season pass rewards. Would've been nice to claim the past season passes rewards, but the extension doesn't seem to work anymore neither in Firefox nor Chrome.

**Comment by HoneyBajjar** [comment]
I  just found out about this extension and added it today. Seems to work for me on Edge up to Season of the Risen. Maybe try to re-add it? What is happening for you when you try to use it?

**Comment by DMWill** [comment]
Also working fine for me in Firefox.  Just like @HoneyBajjar, I can go back to Risen no problem.  That's as far as the API allows after Bungie changed something a while back.  So if you're saying it doesn't work because you can't go back past Risen, that's no longer possible.

Maybe we're missing something.  Can you explain what you're expecting it to do and what is actually happening?

**Comment by nath30** [comment]
the firefox add-on is V1.1.0
the chrome extension is V1.0.1
so it works in firefox, and if you import the firefox add-on into chrome it works.
download it from https://addons.mozilla.org/en-US/firefox/addon/season-pass-pass/ "[Download file](https://addons.mozilla.org/firefox/downloads/file/4123578/season_pass_pass-1.1.0.xpi)"
and change .xpi to .zip extract to a folder and in [chrome://extensions/](chrome://extensions/)  Developer mode>Load Unpacked then select the folder extracted to.

**Comment by joshhunt** [comment]
Note that if you did not hold an entitlement for that season while it was current, I doubt you’ll be able to claim any rewards, even the initial exotic. 

This isn’t a limitation of the extension, but just a quirk of how Season Passes are implemented on Bungie’s backend. 

I’m not sure what Bungie’s expected behaviour is for claiming rewards for seasons you bought after the fact.

**Comment by 677230756E64** [comment]
Update, it works with a VPN. Someone doesn't like certain regions of the world it seems. Whether it's Bungie or the extension dev I've no clue.
