### ISSUE TITLE
Don't see any icons and rewards can't be claimed. 

### ISSUE THREAD

**Issue by RhavensEye** [joshhunt/season-pass-extension#6]
Basically the title. Only thing it's doing for me it's changing name and shows how far did I got through the pass. I'm on firefox.

**Comment by zipman1313** [comment]
I am experiencing the same problem.

**Comment by joshhunt** [comment]
The extension is no longer working as of Season of the Deep. I'm unsure if it's just because something about the site changed that can be worked around, or if the Season Pass API no longer allows previews rewards to be obtained (which can not be worked around).

**Comment by zipman1313** [comment]
Is this something you can look into?

**Comment by Skooravi** [comment]
Just for info, having only discovered this browser extension today, I tested it and was able to claim the seasonal weapon for a couple of seasons I missed at the start of last year. (ie: The exotic at level 1 of the pass). I wasn't able to claim anything else, as folks here have reported. But if one thing can be claimed while others can't, it may suggest some possibility of hope that a fix for all items is plausible. Fingers crossed!

**Comment by frostitution** [comment]
For me the extension only goes as far back as Season of the Risen (start of Witch Queen), so it's still useful to some

**Comment by Beivo** [comment]
im praying this can be fixed, i need to claim things from season of the lost

**Comment by joshhunt** [comment]
Seasons before Risen are no longer claimable through the API at all. There's no working around it - I believe that data has just been deleted on Bungie's side.

The API no longer returns data for season passes for Season of the Lost and earlier:

```
8 Season of the Undying
  Rewards Progression hash 1628407317
  ❌ No reward items in Profile

9 Season of Dawn
  Rewards Progression hash 3256821400
  ❌ No reward items in Profile

10 Season of the Worthy
  Rewards Progression hash 2926321498
  ❌ No reward items in Profile

11 Season of Arrivals
  Rewards Progression hash 1627914615
  ❌ No reward items in Profile

12 Season of the Hunt
  Rewards Progression hash 477676543
  ❌ No reward items in Profile

13 Season of the Chosen
  Rewards Progression hash 4030656982
  ❌ No reward items in Profile

14 Season of the Splicer
  Rewards Progression hash 2726092061
  ❌ No reward items in Profile

15 Season of the Lost
  Rewards Progression hash 4095505052
  ❌ No reward items in Profile

16 Season of the Risen
  Rewards Progression hash 2069932355
  ✔️ Have 161 reward item states

17 Season of the Haunted
  Rewards Progression hash 26079066
  ✔️ Have 161 reward item states

18 Season of Plunder
  Rewards Progression hash 3902035969
  ✔️ Have 161 reward item states

19 Season of the Seraph
  Rewards Progression hash 255193376
  ✔️ Have 161 reward item states

20 Season of Defiance
  Rewards Progression hash 325445472
  ✔️ Have 172 reward item states

21 Season of the Deep
  Rewards Progression hash 3127357249
  ✔️ Have 172 reward item states
```

This is my attempt at trying to forcefully claim rewards from Season of the Lost

My request (Season 2809059428 is Season of the Lost https://data.destinysets.com/i/Season:2809059428):
![image](https://github.com/joshhunt/season-pass-extension/assets/46142/0a4f6872-4c3a-4c7c-9431-2f77f1383534)

And error from Bungie API:

![image](https://github.com/joshhunt/season-pass-extension/assets/46142/9ae371e6-54ca-4081-ad8d-d41836b9c4bc)

I will try to update the extension to remove seasons that it cannot pull rewards from, but otherwise there's not much to do here. Rewards from seasons Lost and prior can not be pulled through the API.
